import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { MainNav } from "@/components/custom/mainNav";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header className="fixed w-full px-2 m-0 sm:px-8 lg:px-16 xl:px-24 bg-background z-20 border-b border-border">
        <MainNav />
      </header>
      <main className="w-full flex flex-col p-4">
        {children}
      </main>
      <footer className="flex justify-center pb-4 text-xl">
        © 2025 Trend.pump
     </footer>
      </body>
    </html>
  );
}
